services:
  django:
    container_name: django_blog
    build:
      context: ./
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:alpine3.19
    container_name: redis


  celery:
    container_name: celery
    build:
      context: ./
    command: celery --app=iconfig.celery_config worker -l INFO 
    volumes:
      - .:/app
    depends_on:
      - redis
      - django
